import{a as v,i as c,S as q}from"./assets/vendor-53a1b719.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const E="44781462-ae4aaccc0a5ec19c0259ffb3b",P="https://pixabay.com/api/",M="photo",x="horizontal",I=!0;async function h(e,o,r){const a=`${P}?key=${E}&q=${encodeURIComponent(e)}&image_type=${M}&orientation=${x}&safesearch=${I}&page=${o}&per_page=${r}`;try{const t=await v.get(a);if(t.status!==200)throw new Error("Network response was not ok");const{hits:s,totalHits:i}=t.data;return{hits:s,totalHits:i}}catch(t){throw console.error(t),t}}const p=document.querySelector(".gallery"),n=document.querySelector('[data-action="load-more"]'),f=document.querySelector(".spinner"),N=document.querySelector(".search-form"),g="is-hidden";let u="",l=1,m=15,y=0;function d(e){e.classList.add(g)}function O(e){e.classList.remove(g)}function w(e,o){e.disabled=!0,o.classList.remove(g)}function L(e,o){e.disabled=!1,o.classList.add(g)}d(n);N.addEventListener("submit",R);async function R(e){e.preventDefault(),p.innerHTML="",l=1;const o=e.currentTarget;if(u=o.elements.search.value.trim(),!u){c.error({title:"Error",message:"Search field cannot be empty!"});return}O(n),w(n,f);try{const{hits:r,totalHits:a}=await h(u,l,m);if(r.length===0){c.warning({title:"No Results",message:"Sorry, there are no images matching your search query."}),d(n);return}y=Math.ceil(a/m),$(r),r.length>0&&r.length!==a?(L(n,f),n.addEventListener("click",b)):d(n),S()}catch(r){console.error(r),c.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{o.reset()}}async function b(){l+=1,w(n,f);try{const{hits:e}=await h(u,l,m);if(e.length===0){c.warning({title:"No Results",message:"Sorry, there are no more images matching your search query."}),d(n);return}$(e),S()}catch(e){console.error(e),c.error({title:"Error",message:"Failed to fetch more images. Please try again later."})}finally{L(n,f),l===y&&(d(n),n.removeEventListener("click",b))}}function $(e){const o=e.map(r=>`<li class="gallery-item">
        <a href="${r.largeImageURL}" data-lightbox="gallery" data-title="${r.tags}">
          <img src="${r.webformatURL}" alt="${r.tags}" />
          <div class="info">
            <p><strong>Likes:</strong> ${r.likes}</p>
            <p><strong>Views:</strong> ${r.views}</p>
            <p><strong>Comments:</strong> ${r.comments}</p>
            <p><strong>Downloads:</strong> ${r.downloads}</p>
          </div>
        </a>
      </li>`).join("");p.insertAdjacentHTML("beforeend",o),H.refresh()}let H=new q(".gallery a",{captionsData:"alt",captionDelay:250});function S(){const{height:e}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
